export const SENSITIVE_TERMS: readonly string[] = [
  "2fa",
  "archive",
  "bank",
  "billing",
  "buy",
  "cancel",
  "card",
  "charge",
  "checkout",
  "close",
  "credential",
  "deactivate",
  "delete",
  "destroy",
  "downgrade",
  "erase",
  "grant",
  "iban",
  "impersonate",
  "invoice",
  "invite",
  "merge",
  "mfa",
  "overwrite",
  "owner",
  "password",
  "pay",
  "payment",
  "payout",
  "permanently",
  "permission",
  "plan",
  "production",
  "purchase",
  "purge",
  "recovery",
  "refund",
  "remove",
  "reset",
  "revoke",
  "role",
  "sepa",
  "ssn",
  "subscribe",
  "suspend",
  "tax",
  "terminate",
  "totp",
  "transfer",
  "unsubscribe",
  "upgrade",
  "wipe",
  "wire",
];

const SENSITIVE_NAME = new RegExp(`\\b(?:${SENSITIVE_TERMS.join("|")})\\b`, "i");

export function isSensitiveText(value: string): boolean {
  return SENSITIVE_NAME.test(value);
}
